# Generated by Django 5.0.6 on 2024-06-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_coinoutput_price_alter_coinoutput_price_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinoutput',
            name='circulating_supply',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='coinoutput',
            name='diluted_market_cap',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='coinoutput',
            name='market_cap',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='coinoutput',
            name='market_cap_rank',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='coinoutput',
            name='price',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='coinoutput',
            name='total_supply',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='coinoutput',
            name='volume',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='coinoutput',
            name='volume_change',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='coinoutput',
            name='volume_rank',
            field=models.CharField(max_length=20),
        ),
    ]
